# The Guild Org Master Labels

- name: 'automerge'
  color: '84e1f9'

- name: 'good first issue'
  color: '31be4f'

- name: 'kind/bug'
  color: '0052cc'
  description: 'Bug :-('
  from_name: 'bug'

- name: 'kind/enhancement'
  color: '0052cc'
  description: 'New feature or request'
  from_name: 'enhancement'

- name: 'kind/docs'
  color: '0052cc'
  description: 'Improvements or additions to documentation'
  from_name: 'docs'

- name: 'kind/question'
  color: '0052cc'
  description: 'Improvements or additions to documentation'

- name: 'stage/0-issue-prerequisites'
  color: 'a3a3a3'
  description: 'Needs more information before we can start working on it'
  from_name: 'needs reproduction'

- name: 'stage/1-reproduction'
  color: 'db5858'
  description: 'A reproduction exists'

- name: 'stage/2-failing-test'
  color: 'd6650f'
  description: 'A failing test was created that describes the issue'
  
- name: 'stage/3-local-solution'
  color: 'e6e610'
  description: 'A user has a possible solution that solves the issue'
  
- name: 'stage/4-pull-request'
  color: 'b4e610'
  description: 'A pull request has been opened that aims to solve the issue'
  
- name: 'stage/5-alpha-release-testing'
  color: '89e610'
  description: 'A pull request that aims to solve the issue has been merged and there is an alpha version to we can test with'      
  
- name: 'stage/6-released'
  color: '0fed07'
  description: 'The issue has been solved on a released version of the library'        

- name: 'waiting-for-answer'
  color: 'fef2c0'
  description: 'Waiting for answer from author'

- name: 'waiting-for-release'
  color: 'b6f3b1'
  description: 'Fixed/resolved, and waiting for the next stable release'

- name: 'duplicate'
  color: 'cfd8d7'
  description: 'This issue or pull request already exists'

- name: 'wontfix'
  color: '000000'
  description: 'This will not be worked on for now and is not in our backlog'
  from_name: 'wontfix'

- name: 'help wanted'
  color: '008672'
  description: 'Extra attention is needed'
  from_name: 'needs-help'

- name: 'process/candidate'
  color: '790e5d'
  description: 'Candidate for next Milestone.'

- name: 'status/backlog'
  color: 'b60205'
  description: 'In the backlog'

- name: 'status/wip'
  color: 'fbca04'
  description: 'Work In Progress'

- name: 'status/resolved'
  color: '0e8a16'
  description: 'The work has been completed'

- name: 'status/blocked'
  color: '243b29'
  description: 'This task is blocked by another dependant task'

- name: 'status/parked'
  color: 'bfd4f2'
  description: 'This task has been temporarily parked - No work is currently underway'

- name: 'status/pending-verification'
  color: 'c5def5'
  description: 'This task is complete but pending verification from the user'
